name: CICD try1
on: push
jobs:
   Demo_build:
      runs-on:
         ubuntu-latest
      steps:
         - name: Print input name on STDOUT
           run: echo $(whoami)
   Demo_test:
      runs-on:
         ubuntu-latest
      steps:
         - name: Print input name on STDOUT
           run: echo $(whoami)         
   

    
    
